### ISSUE TITLE
Non-location communities?

### ISSUE THREAD

**Issue by namangoel1** [fossasia/fossasia-communities#72]
There are some communities that are based on language, for example [Arabeyes](http://www.arabeyes.org/). They are not based in any location nor have any official headquarters. Where do they go? Do they qualify being a part of this list? Thanks!

**Comment by mariobehling** [comment]
Please use the location, that comes up where the main authors, contributors or developers are from. Alternatively you can search in the domain registry. Then use the location of the person who registered the domain.
