### ISSUE TITLE
Delete not relevant sites

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-communities#88]
Some groups are non Open Source tech groups, company pages or groups not relevant to FOSS. Please delete references to the following: 
coLAB
Mozilla CAMBODIA
Community Health Information Tracking System
KolkataNET
Ceviz
Mozilla Turkey
Google Developers Group Hyderabad
Dubai GTUG
Dubai SharePoint User Group
Mozilla India
ORACLE USER GROUP IN THAILAND
All India Oracle User Group
Oracle VM SIG
Internet Society of Armenia(ISOC AM)
MozTW - Mozilla Taiwan Community
HanGee
Mozilla Nepal
Ubuntu Malaysia
Ubuntu Vietnam

**Comment by amroto** [comment]
https://github.com/fossasia/fossasia-communities/pull/89
Can you merge this
