### ISSUE TITLE
Invite/Add students to GCI team of FOSSASIA

### ISSUE THREAD

**Issue by mariobehling** [fossasia/fossasia-communities#90]
@samarjeet27 @ty221 Are you interested to help and invite all students that participated in FOSSASIA GCI to become members of the GCI Students Team on Github? 
I gave you temp. extended rights. Would be great if you help.
Please add people to the team here: https://github.com/orgs/fossasia/teams/fossasia-gci-students

**Comment by samarjeet27** [comment]
@mariobehling yup

**Comment by ty221** [comment]
@mariobehling Surely, will work on that :D

**Comment by samarjeet27** [comment]
@mariobehling, At the moment I can already add to Web Developers team, could you add the right to FOSSASIA-GCI-Students team ?

**Comment by ty221** [comment]
@mariobehling Unfortunately, me and @samarjeet27 do not have access to add people to team :/

**Comment by mariobehling** [comment]
adding you temp. to owners

**Comment by ty221** [comment]
@mariobehling Ok, thank you. Will add

**Comment by samarjeet27** [comment]
@mariobehling, guess all have been added

**Comment by ty221** [comment]
@mariobehling Can we close that?
